export default {
  "results": [
    {
      "ticker": "X:00USD",
      "name": "00 Token - United States dollar",
      "market": "crypto",
      "locale": "global",
      "active": true,
      "currency_symbol": "USD",
      "currency_name": "United States dollar",
      "base_currency_symbol": "00",
      "base_currency_name": "00 Token",
      "last_updated_utc": "2017-01-01T00:00:00Z"
    },
    {
      "ticker": "X:1INCHUSD",
      "name": "1inch - United States dollar",
      "market": "crypto",
      "locale": "global",
      "active": true,
      "currency_symbol": "USD",
      "currency_name": "United States dollar",
      "base_currency_symbol": "1INCH",
      "base_currency_name": "1inch",
      "last_updated_utc": "2017-01-01T00:00:00Z"
    },
    {
      "ticker": "X:A8USD",
      "name": "Ancient8 - United States dollar",
      "market": "crypto",
      "locale": "global",
      "active": true,
      "currency_symbol": "USD",
      "currency_name": "United States dollar",
      "base_currency_symbol": "A8",
      "base_currency_name": "Ancient8",
      "last_updated_utc": "2017-01-01T00:00:00Z"
    },
    {
      "ticker": "X:AAVEUSD",
      "name": "Aave - United States dollar",
      "market": "crypto",
      "locale": "global",
      "active": true,
      "currency_symbol": "USD",
      "currency_name": "United States dollar",
      "base_currency_symbol": "AAVE",
      "base_currency_name": "Aave",
      "last_updated_utc": "2017-01-01T00:00:00Z"
    },
    {
      "ticker": "X:ABTUSD",
      "name": "Arcblock - United States dollar",
      "market": "crypto",
      "locale": "global",
      "active": true,
      "currency_symbol": "USD",
      "currency_name": "United States dollar",
      "base_currency_symbol": "ABT",
      "base_currency_name": "Arcblock",
      "last_updated_utc": "2017-01-01T00:00:00Z"
    },
    {
      "ticker": "X:ACAUSD",
      "name": "Acala - United States dollar",
      "market": "crypto",
      "locale": "global",
      "active": true,
      "currency_symbol": "USD",
      "currency_name": "United States dollar",
      "base_currency_symbol": "ACA",
      "base_currency_name": "Acala",
      "last_updated_utc": "2017-01-01T00:00:00Z"
    },
    {
      "ticker": "X:ACHUSD",
      "name": "Alchemy Pay - United States dollar",
      "market": "crypto",
      "locale": "global",
      "active": true,
      "currency_symbol": "USD",
      "currency_name": "United States dollar",
      "base_currency_symbol": "ACH",
      "base_currency_name": "Alchemy Pay",
      "last_updated_utc": "2017-01-01T00:00:00Z"
    },
    {
      "ticker": "X:ACSUSD",
      "name": "Access Protocol - United States dollar",
      "market": "crypto",
      "locale": "global",
      "active": true,
      "currency_symbol": "USD",
      "currency_name": "United States dollar",
      "base_currency_symbol": "ACS",
      "base_currency_name": "Access Protocol",
      "last_updated_utc": "2017-01-01T00:00:00Z"
    },
    {
      "ticker": "X:ACXUSD",
      "name": "Across Protocol - United States dollar",
      "market": "crypto",
      "locale": "global",
      "active": true,
      "currency_symbol": "USD",
      "currency_name": "United States dollar",
      "base_currency_symbol": "ACX",
      "base_currency_name": "Across Protocol",
      "last_updated_utc": "2017-01-01T00:00:00Z"
    },
    {
      "ticker": "X:ADAUSD",
      "name": "Cardano - United States dollar",
      "market": "crypto",
      "locale": "global",
      "active": true,
      "currency_symbol": "USD",
      "currency_name": "United States dollar",
      "base_currency_symbol": "ADA",
      "base_currency_name": "Cardano",
      "last_updated_utc": "2017-01-01T00:00:00Z"
    },
    {
      "ticker": "X:ADXUSD",
      "name": "AdEx - United States dollar",
      "market": "crypto",
      "locale": "global",
      "active": true,
      "currency_symbol": "USD",
      "currency_name": "United States dollar",
      "base_currency_symbol": "ADX",
      "base_currency_name": "AdEx",
      "last_updated_utc": "2017-01-01T00:00:00Z"
    },
    {
      "ticker": "X:AERGOUSD",
      "name": "Aergo - United States dollar",
      "market": "crypto",
      "locale": "global",
      "active": true,
      "currency_symbol": "USD",
      "currency_name": "United States dollar",
      "base_currency_symbol": "AERGO",
      "base_currency_name": "Aergo",
      "last_updated_utc": "2017-01-01T00:00:00Z"
    },
    {
      "ticker": "X:AEROUSD",
      "name": "Aerodome Finance - United States dollar",
      "market": "crypto",
      "locale": "global",
      "active": true,
      "currency_symbol": "USD",
      "currency_name": "United States dollar",
      "base_currency_symbol": "AERO",
      "base_currency_name": "Aerodome Finance",
      "last_updated_utc": "2017-01-01T00:00:00Z"
    },
    {
      "ticker": "X:AEVOUSD",
      "name": "Aevo - United States dollar",
      "market": "crypto",
      "locale": "global",
      "active": true,
      "currency_symbol": "USD",
      "currency_name": "United States dollar",
      "base_currency_symbol": "AEVO",
      "base_currency_name": "Aevo",
      "last_updated_utc": "2017-01-01T00:00:00Z"
    },
    {
      "ticker": "X:AGLDUSD",
      "name": "Adventure Gold - United States dollar",
      "market": "crypto",
      "locale": "global",
      "active": true,
      "currency_symbol": "USD",
      "currency_name": "United States dollar",
      "base_currency_symbol": "AGLD",
      "base_currency_name": "Adventure Gold",
      "last_updated_utc": "2017-01-01T00:00:00Z"
    },
    {
      "ticker": "X:AIOZUSD",
      "name": "AIOZ Network - United States dollar",
      "market": "crypto",
      "locale": "global",
      "active": true,
      "currency_symbol": "USD",
      "currency_name": "United States dollar",
      "base_currency_symbol": "AIOZ",
      "base_currency_name": "AIOZ Network",
      "last_updated_utc": "2017-01-01T00:00:00Z"
    },
    {
      "ticker": "X:AIRUSD",
      "name": "AIRian - United States dollar",
      "market": "crypto",
      "locale": "global",
      "active": true,
      "currency_symbol": "USD",
      "currency_name": "United States dollar",
      "base_currency_symbol": "AIR",
      "base_currency_name": "AIRian",
      "last_updated_utc": "2017-01-01T00:00:00Z"
    },
    {
      "ticker": "X:AKTEUR",
      "name": "Akash Network - Euro",
      "market": "crypto",
      "locale": "global",
      "active": true,
      "currency_symbol": "EUR",
      "currency_name": "Euro",
      "base_currency_symbol": "AKT",
      "base_currency_name": "Akash Network",
      "last_updated_utc": "2017-01-01T00:00:00Z"
    },
    {
      "ticker": "X:ALBTUSD",
      "name": "AllianceBlock - United States dollar",
      "market": "crypto",
      "locale": "global",
      "active": true,
      "currency_symbol": "USD",
      "currency_name": "United States dollar",
      "base_currency_symbol": "ALBT",
      "base_currency_name": "AllianceBlock",
      "last_updated_utc": "2017-01-01T00:00:00Z"
    },
    {
      "ticker": "X:ALCXUSD",
      "name": "Alchemix - United States dollar",
      "market": "crypto",
      "locale": "global",
      "active": true,
      "currency_symbol": "USD",
      "currency_name": "United States dollar",
      "base_currency_symbol": "ALCX",
      "base_currency_name": "Alchemix",
      "last_updated_utc": "2017-01-01T00:00:00Z"
    },
    {
      "ticker": "X:ALEOUSD",
      "name": "Aleo - United States dollar",
      "market": "crypto",
      "locale": "global",
      "active": true,
      "currency_symbol": "USD",
      "currency_name": "United States dollar",
      "base_currency_symbol": "ALEO",
      "base_currency_name": "Aleo",
      "last_updated_utc": "2017-01-01T00:00:00Z"
    },
    {
      "ticker": "X:ALEPHUSD",
      "name": "Aleph.im v2 - United States dollar",
      "market": "crypto",
      "locale": "global",
      "active": true,
      "currency_symbol": "USD",
      "currency_name": "United States dollar",
      "base_currency_symbol": "ALEPH",
      "base_currency_name": "Aleph.im v2",
      "last_updated_utc": "2017-01-01T00:00:00Z"
    },
    {
      "ticker": "X:ALGOUSD",
      "name": "Algorand - United States dollar",
      "market": "crypto",
      "locale": "global",
      "active": true,
      "currency_symbol": "USD",
      "currency_name": "United States dollar",
      "base_currency_symbol": "ALGO",
      "base_currency_name": "Algorand",
      "last_updated_utc": "2017-01-01T00:00:00Z"
    },
    {
      "ticker": "X:ALICEUSD",
      "name": "MyNeighborAlice - United States dollar",
      "market": "crypto",
      "locale": "global",
      "active": true,
      "currency_symbol": "USD",
      "currency_name": "United States dollar",
      "base_currency_symbol": "ALICE",
      "base_currency_name": "MyNeighborAlice",
      "last_updated_utc": "2017-01-01T00:00:00Z"
    },
    {
      "ticker": "X:ALPHAUSD",
      "name": "Stella - United States dollar",
      "market": "crypto",
      "locale": "global",
      "active": true,
      "currency_symbol": "USD",
      "currency_name": "United States dollar",
      "base_currency_symbol": "ALPHA",
      "base_currency_name": "Stella",
      "last_updated_utc": "2017-01-01T00:00:00Z"
    },
    {
      "ticker": "X:ALT11M2507USD",
      "name": "ALT11M2507 - United States dollar",
      "market": "crypto",
      "locale": "global",
      "active": true,
      "currency_symbol": "USD",
      "currency_name": "United States dollar",
      "base_currency_symbol": "ALT11M2507",
      "base_currency_name": "ALT11M2507",
      "last_updated_utc": "2017-01-01T00:00:00Z"
    },
    {
      "ticker": "X:ALT2612USD",
      "name": "ALT2612 - United States dollar",
      "market": "crypto",
      "locale": "global",
      "active": true,
      "currency_symbol": "USD",
      "currency_name": "United States dollar",
      "base_currency_symbol": "ALT2612",
      "base_currency_name": "ALT2612",
      "last_updated_utc": "2017-01-01T00:00:00Z"
    },
    {
      "ticker": "X:ALTUSD",
      "name": "AltLayer - United States dollar",
      "market": "crypto",
      "locale": "global",
      "active": true,
      "currency_symbol": "USD",
      "currency_name": "United States dollar",
      "base_currency_symbol": "ALT",
      "base_currency_name": "AltLayer",
      "last_updated_utc": "2017-01-01T00:00:00Z"
    },
    {
      "ticker": "X:AMPUSD",
      "name": "Amp - United States dollar",
      "market": "crypto",
      "locale": "global",
      "active": true,
      "currency_symbol": "USD",
      "currency_name": "United States dollar",
      "base_currency_symbol": "AMP",
      "base_currency_name": "Amp",
      "last_updated_utc": "2017-01-01T00:00:00Z"
    },
    {
      "ticker": "X:ANKRUSD",
      "name": "Ankr - United States dollar",
      "market": "crypto",
      "locale": "global",
      "active": true,
      "currency_symbol": "USD",
      "currency_name": "United States dollar",
      "base_currency_symbol": "ANKR",
      "base_currency_name": "Ankr",
      "last_updated_utc": "2017-01-01T00:00:00Z"
    }
  ],
  "status": "OK",
  "request_id": "38b4a97e4fdc90548ea4f58516f9d073",
  "count": 30,
  "next_url": ""
}